### ISSUE TITLE
module Xenium Ranger

### ISSUE THREAD

**Issue by heylf** [nf-core/spatialxe#10]
### Description of feature

https://www.10xgenomics.com/support/software/xenium-ranger/latest

**!! Please check with nf-core and 10x how to implement this as a module to avoid copy right and maintenance issues (check license again) !!**

**Comment by heylf** [comment]
- [ ] How to scale it up? How do we handle parallelization?

**Comment by khersameesh24** [comment]
Extensive testing of the xeniumranger modules remain, additions to nf-tests required for more meaningful and corner case testing along with baysor integration.
